print("name latter finder... \n")
first_name =(input("Enter your first Name \n"))
last_name =(input("Enter your last Name \n"))
first_name_len=len(first_name)
last_name_len = len(last_name)
total_later = str(first_name_len+last_name_len)
first_name_str=str(first_name_len)
last_names_str=str(last_name_len)
print("Your first name has "+first_name_str+"  latter\n")
print("Your last name has "+last_names_str+" latter\n")
print("Your name "+first_name+" "+last_name+" has total number of latter is "+total_later)                 